EDUHOME/Areas/Admin/Controllers/TeachersController.cs
using Allup.Data;
using EDUHOME.Areas.Admin.Data;
using EDUHOME.Areas.Admin.Models;
using EDUHOME.DAL;
using EDUHOME.DAL.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.DependencyResolver;
using NuGet.Protocol.Plugins;
using System.Xml.Linq;

namespace EDUHOME.Areas.Admin.Controllers
{
    public class TeachersController : BaseController
    {
        private readonly AppDbContext _dbContext;

        public TeachersController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            var teachers = await _dbContext.Teachers
                .ToListAsync();

            return View(teachers);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TeacherCreateViewModel model)
        {
            if (!ModelState.IsValid)
                return View();

            if (!model.Image.IsImage())
            {
                ModelState.AddModelError("", "Shekil Secmelisiz");
                return View();
            }

            if (!model.Image.IsAllowedSize(10))
            {
                ModelState.AddModelError("", "Shekilin olcusu 10 mbdan az omalidi");
                return View();
            }

            var unicalName = await model.Image.GenerateFile(Constants.TeacherPath);

            var teacher = new Teacher
            {
                Name = model.Name,
                Profession = model.Profession,
                About = model.About,
                Degree = model.Degree,
                Experience = model.Experience,
                Hobbies = model.Hobbies,
                Faculty = model.Faculty,
                Mail = model.Mail,
                Skype = model.Skype,
                Number = model.Number,
                Language = model.Language,
                Teamleader = model.Teamleader,
                Development = model.Development,
                Design = model.Design,
                Innovation = model.Innovation,
                Communication = model.Communication,
                Imageurl = unicalName,
            };

            await _dbContext.Teachers.AddAsync(teacher);

            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id == null) return BadRequest();

            var teacher = await _dbContext.Teachers
                .Where(teacher => teacher.Id == id)
                .FirstOrDefaultAsync();

            var model = new TeacherUpdateViewModel
            {
                Name = teacher.Name,
                Profession = teacher.Profession,
                About = teacher.About,
                Degree = teacher.Degree,
                Experience = teacher.Experience,
                Hobbies = teacher.Hobbies,
                Faculty = teacher.Faculty,
                Mail = teacher.Mail,
                Skype = teacher.Skype,
                Number = teacher.Number,
                Language = teacher.Language,
                Teamleader = teacher.Teamleader,
                Development = teacher.Development,
                Design = teacher.Design,
                Innovation = teacher.Innovation,
                Communication = teacher.Communication,
                Imageurl = teacher.Imageurl,
                IsDeleted = teacher.IsDeleted,  
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, TeacherUpdateViewModel model)
        {
            if (id == null) return BadRequest();

            var existTeacher = await _dbContext.Teachers
                .Where(teacher => teacher.Id == id)
                .FirstOrDefaultAsync();

            var viewModel = new TeacherUpdateViewModel
            {
                Name = existTeacher.Name,
                Profession = existTeacher.Profession,
                About = existTeacher.About,
                Degree = existTeacher.Degree,
                Experience = existTeacher.Experience,
                Hobbies = existTeacher.Hobbies,
                Faculty = existTeacher.Faculty,
                Mail = existTeacher.Mail,
                Skype = existTeacher.Skype,
                Number = existTeacher.Number,
                Language = existTeacher.Language,
                Teamleader = existTeacher.Teamleader,
                Development = existTeacher.Development,
                Design = existTeacher.Design,
                Innovation = existTeacher.Innovation,
                Communication = existTeacher.Communication,
                Imageurl = existTeacher.Imageurl,
                IsDeleted = existTeacher.IsDeleted, 
            };

            if (!ModelState.IsValid) return View(viewModel);

            if (model.Image != null)
            {
                if (!model.Image.IsImage())
                {
                    ModelState.AddModelError("Image", "Shekil Secmelisiz");
                    return View(viewModel);
                }

                if (!model.Image.IsAllowedSize(10))
                {
                    ModelState.AddModelError("Image", "Shekilin olcusu 10 mbdan az omalidi");
                    return View(viewModel);
                }

                var path = Path.Combine(Constants.RootPath, "assets", "images", "teacher", existTeacher.Imageurl);

                if (System.IO.File.Exists(path))
                    System.IO.File.Delete(path);

                var unicalName = await model.Image.GenerateFile(Constants.TeacherPath);

                existTeacher.Imageurl = unicalName;
            }

            existTeacher.IsDeleted = model.IsDeleted;
            existTeacher.Name = model.Name;
            existTeacher.Profession = model.Profession;
            existTeacher.About = model.About;
            existTeacher.Degree = model.Degree;
            existTeacher.Experience = model.Experience;
            existTeacher.Hobbies = model.Hobbies;
            existTeacher.Faculty = model.Faculty;
            existTeacher.Mail = model.Mail;
            existTeacher.Skype = model.Skype;
            existTeacher.Number = model.Number;
            existTeacher.Language = model.Language;
            existTeacher.Teamleader = model.Teamleader;
            existTeacher.Development = model.Development;
            existTeacher.Design = model.Design;
            existTeacher.Innovation = model.Innovation;
            existTeacher.Communication = model.Communication;

            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return BadRequest();

            var existTeacher = await _dbContext.Teachers
                .Where(teacher => teacher.Id == id)
                .FirstOrDefaultAsync();

            if (existTeacher == null) return BadRequest();

            _dbContext.Teachers.Remove(existTeacher);

            var path = Path.Combine(Constants.RootPath, "assets", "images", "teacher", existTeacher.Imageurl);

            if (System.IO.File.Exists(path))
                System.IO.File.Delete(path);

            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
    }
}

EDUHOME/Controllers/TeachersController.cs
using EDUHOME.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EDUHOME.Controllers
{
    public class TeachersController : Controller
    {
        private readonly AppDbContext _dbContext;

        public TeachersController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var teachers = _dbContext.Teachers.ToList();

            return View(teachers);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null) return NotFound();  

            var teacher = await _dbContext.Teachers
                .Where(x => x.Id == id)
                .FirstOrDefaultAsync(); 

            return View(teacher);
        }

    }
}

EDUHOME/Views/Teachers/Details.cshtml
@model Teacher
<!-- Banner Area Start -->
<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>teachers / details</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Teacher Start -->
<div class="teacher-details-area pt-150 pb-60">
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-sm-5 col-xs-12">
                <div class="teacher-details-img">
                    <img src="~/assets/images/teacher/@Model.Imageurl" alt="teacher">
                </div>
            </div>
            <div class="col-md-7 col-sm-7 col-xs-12">
                <div class="teacher-details-content ml-50">
                    <h2>@Model.Name</h2>
                    <h5>@Model.Profession</h5>
                    <h4>about me</h4>
                    <p>@Model.About</p>
                    <ul>
                        <li><span>degree: </span>@Model.Degree</li>
                        <li><span>experience: </span>@Model.Experience</li>
                        <li><span>hobbies: </span>@Model.Hobbies</li>
                        <li><span>faculty: </span>@Model.Faculty</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-4">
                <div class="teacher-contact">
                    <h4>contact information</h4>
                    <p><span>mail me : </span>@Model.Mail</p>
                    <p><span>make a call : </span>@Model.Number</p>
                    <p><span>skype : </span> @Model.Skype</p>
                    <ul>
                        <li><a href="https://www.facebook.com/devitems/?ref=bookmarks"><i class="zmdi zmdi-facebook"></i></a></li>
                        <li><a href="https://www.pinterest.com/devitemsllc/"><i class="zmdi zmdi-pinterest"></i></a></li>
                        <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                        <li><a href="https://twitter.com/devitemsllc"><i class="zmdi zmdi-twitter"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-9 col-sm-8">
                <div class="skill-area">
                    <h4>skills</h4>
                </div>
                <div class="skill-wrapper">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>language</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width: @Model.Language%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@Model.Language%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>team leader</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width: @Model.Teamleader%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@Model.Teamleader%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>development</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width:@Model.Development%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@Model.Development%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>design</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width: @Model.Design%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@Model.Design%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>innovation</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width: @Model.Innovation%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@Model.Innovation%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>communication</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width: @Model.Communication%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@Model.Communication%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Teacher End -->
<!-- Subscribe Start -->
<div class="subscribe-area pt-60 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="subscribe-content section-title text-center">
                    <h2>subscribe our newsletter</h2>
                    <p>I must explain to you how all this mistaken idea </p>
                </div>
                <div class="newsletter-form mc_embed_signup">
                    <form action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <div id="mc_embed_signup_scroll" class="mc-form">
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your e-mail address" required>
                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div class="mc-news" aria-hidden="true"><input type="text" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" tabindex="-1" value=""></div>
                            <button id="mc-embedded-subscribe" class="default-btn" type="submit" name="subscribe"><span>subscribe</span></button>
                        </div>
                    </form>
                    <!-- mailchimp-alerts Start -->
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                        <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                        <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                    </div>
                    <!-- mailchimp-alerts end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Subscribe End -->

EDUHOME/Views/Teachers/Index.cshtml
@model List<Teacher>
<!-- Banner Area Start -->
<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>our teachers</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Teacher Start -->
<div class="teacher-area pt-150 pb-105">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="single-teacher mb-45">
                    <div class="single-teacher-img">
                            <a asp-controller="Teachers" asp-action="Details" asp-route-id="@item.Id"><img src="~/assets/images/teacher/@item.Imageurl" alt="teacher"></a>
                    </div>
                    <div class="single-teacher-content text-center">
                            <h2><a asp-controller="Teachers" asp-action="Details" asp-route-id="@item.Id">@item.Name</a></h2>
                        <h4>@item.Profession</h4>
                        <ul>
                            <li><a href="https://www.facebook.com/devitems/?ref=bookmarks"><i class="zmdi zmdi-facebook"></i></a></li>
                            <li><a href="https://www.pinterest.com/devitemsllc/"><i class="zmdi zmdi-pinterest"></i></a></li>
                            <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                            <li><a href="https://twitter.com/devitemsllc"><i class="zmdi zmdi-twitter"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            }
           
        </div>
    </div>
</div>
<!-- Teacher End -->
<!-- Subscribe Start -->
<div class="subscribe-area pt-60 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="subscribe-content section-title text-center">
                    <h2>subscribe our newsletter</h2>
                    <p>I must explain to you how all this mistaken idea </p>
                </div>
                <div class="newsletter-form mc_embed_signup">
                    <form action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <div id="mc_embed_signup_scroll" class="mc-form">
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your e-mail address" required>
                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div class="mc-news" aria-hidden="true"><input type="text" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" tabindex="-1" value=""></div>
                            <button id="mc-embedded-subscribe" class="default-btn" type="submit" name="subscribe"><span>subscribe</span></button>
                        </div>
                    </form>
                    <!-- mailchimp-alerts Start -->
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                        <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                        <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                    </div>
                    <!-- mailchimp-alerts end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Subscribe End -->