EDUHOME/Models/ContactMessageViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EDUHOME.Models
{
    public class ContactMessageViewModel
    {
        public string Name { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
    }
}

EDUHOME/Areas/Admin/Controllers/ContactMessagesController.cs
using EDUHOME.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EDUHOME.Areas.Admin.Controllers
{
    public class ContactMessagesController : BaseController
    {
        private readonly AppDbContext _dbContext;

        public ContactMessagesController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            var messages = await _dbContext.ContactMessages
                .ToListAsync();

            return View(messages);
        }

        public async Task<IActionResult> Details(int id)
        {
            var message = await _dbContext.ContactMessages
                .Where(message => message.Id == id)
                .FirstOrDefaultAsync();

            if(message == null) return View();   

            message.IsRead = true;

            await _dbContext.SaveChangesAsync();

            return View(message);
        }
    }
}

EDUHOME/Areas/Admin/Views/Shared/Components/ContactMessage/Default.cshtml
@model List<ContactMessage>

@{
    var isRadeyMessages = Model.All(message => message.IsRead == true);
}
<li class="nav-item dropdown mr-1">
    <a class="nav-link count-indicator dropdown-toggle d-flex justify-content-center align-items-center" id="messageDropdown" href="#" data-toggle="dropdown">
        <i class="mdi mdi-message-text mx-0"></i>
        <span class=@(isRadeyMessages ? "" :"count")> </span>
    </a>
    <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="messageDropdown">
        <p class="mb-0 font-weight-normal float-left dropdown-header">Messages</p>
        @foreach (var item in Model)
        {
            <a asp-controller="ContactMessages" asp-action="Details" asp-route-id="@item.Id" class="dropdown-item">
                <div class="item-content flex-grow">
                    <h6 class="ellipsis font-weight-normal">
                        @item.Name
                    </h6>
                    <p class="font-weight-light small-text text-muted mb-0">
                        @(item.Message.Length > 25 ? item.Message.Substring(0, 25) : item.Message)
                    </p>
                </div>
            </a>
        }
    </div>
</li>